services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: northwind_olap
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=northwind_db
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=password
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  ingestion:
    image: python:3.11-slim
    container_name: northwind_ingestion
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - BUCKET_NAME=northwind-data-pipeline-403783416520
      - AWS_REGION=us-east-1
    command: >
      sh -c "
        pip install --no-cache-dir -q boto3 clickhouse-connect python-dotenv &&
        python scripts/wait_for_clickhouse.py &&
        python scripts/ingest_data.py
      "
    depends_on:
      - clickhouse

  dbt:
    image: python:3.11-slim
    container_name: northwind_dbt
    volumes:
      - ./dbt_project:/dbt
      - ./scripts:/scripts
    working_dir: /dbt
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=northwind_db
    command: >
      sh -c "
        pip install --no-cache-dir -q dbt-core dbt-clickhouse &&
        python /scripts/wait_for_clickhouse.py &&
        dbt run --profiles-dir .
      "
    depends_on:
      - clickhouse

  streamlit:
    image: python:3.11-slim
    container_name: northwind_frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_DB=northwind_db
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: >
      sh -c "
        pip install --no-cache-dir -q streamlit pandas clickhouse-connect python-dotenv &&
        python3 -m streamlit run streamlit_app/app.py --server.port=8501 --server.address=0.0.0.0
      "
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:
