olist_profile:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST', 'clickhouse') }}"
      port: 8123
      user: "{{ env_var('CLICKHOUSE_USER', 'admin') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', 'password') }}"
      schema: "{{ env_var('CLICKHOUSE_DB', 'olist_db') }}"
      secure: false
      verify: false
